### ISSUE TITLE
Cannot exit "MatlabShowVariable"

### ISSUE THREAD

**Issue by tdehaeze** [JeroenMulkers/matvim#1]
Hi,

Thanks for this amazing plugin! :)

I have a problem with the MatlabShowVariable function. It works but I can't quit it, when I type "q" it just goes to the next line...

Any idea how to fix this ?

Thank you very much

**Comment by JeroenMulkers** [comment]
Thank you for your interest in this plugin.

Normally the result should be printed on the screen, followed by "Press ENTER or type command to continue".  When I press Enter, I return back to vim's normal mode". When I press "q" (instead of Enter) I trigger the recording functionality of vim, as it should.

Do you have the same problem for `MatlabRunLine`?
Does "Press ENTER or type command to continue" appears on your screen?
What happens if you run `:echo "Hello\nThere\n"`?

**Comment by tdehaeze** [comment]
When I got "Press ENTER or type command to continue" it's working perfectly.

My problem appears when I want to display a large Vector, in this case I can go up and down using "j" and "k". But "q" doesn't quit the display of the vector but goes down instead.

I need to go to the bottom of the vector and then "q" is working. Even "C-c" doesn't work. So when my vector has 100.000 elements, it's very long to go to the bottom 😄

**Comment by JeroenMulkers** [comment]
Ok, I see your problem know. Pressing G a single time can bring you down without holding down the "j" or "down" key. However this is not really a nice solution because the whole message will still be printed, although very fast. 

I did not spend much time fixing this issue because I do not see the point of printing large datasets on the screen. Of course, it could happen by accident (e.g. by forgetting an ';' at the end of a line), which is annoying.

**Comment by tdehaeze** [comment]
Nice workaround! Thank you very much 😃  👍

**Comment by JeroenMulkers** [comment]
Check also d21d0c3
